### ISSUE TITLE
RabbitMQ high resource usage issue

### ISSUE THREAD

**Issue by ghost** [INAETICS/Drones-Simulator#36]
Seems to be caused by subscribers which spam basicConsume. This is confirmed by the fact that running just a publisher, does not raise resource level to unexpected levels.

**Comment by jjkester** [comment]
As it turned out, you have to start a consumer only once (RabbitMQ starts a thread itself). This did not seem to work because after binding a new exchange to a queue (adding a topic to a subscriber) you have to restart the consumer. This should be fixed now.
