### ISSUE TITLE
RabbitMQ expose list of handlers per messagetype

### ISSUE THREAD

**Issue by ghost** [INAETICS/Drones-Simulator#52]
`void addHandler(Class<? extends Message> messageClass, MessageHandler handler); ` Adds the handler to the current handlers for that message type.
`void addHandlers(Class<? extends Message> messageClass, Collection<MessageHandler> handlers); ` Adds the handlers to the current handlers for that message type.
`void removeHandler(Class<? extends Message> messageClass, MessageHandler handler);` Only removes the specified handler from the current list of handlers for that messagetype

**Comment by jjkester** [comment]
It seems that this was already present in the implementation (except for the second method, for which a new issue can be opened if needed).
